### ISSUE TITLE
How to use spin with expected artifacts.

### ISSUE THREAD

**Issue by dodizzle** [spinnaker/spin#102]
I'm using spin built from current master.
If I save a pipeline with artifacts I am operating under the assumption that spinnaker will generate the expectedArtifacts.id

ie.
  "expectedArtifacts": [
    {
      "defaultArtifact": {},
      "id": "3b534ca2-5e45-458c-be8a-9c5b19c64132"

However that same id  "3b534ca2-5e45-458c-be8a-9c5b19c64132" must match in stages.inputArtifacts.id

ie.
  "stages": [
    {
      "expectedArtifacts": [
        { },
          "useDefaultArtifact": false
        }
      ],
      "inputArtifacts": [
        {
          "account": "sandbox-charts",
          "id": "3b534ca2-5e45-458c-be8a-9c5b19c64132"

How do I refer to expectedArtifacts.id which at save time is null in stages.inputArtifacts.id.

**Comment by jtk54** [comment]
You can define an id for the expected artifact in the pipeline definition you are submitting with `spin`. They have to be unique within a given pipeline, but that is the only constraint.
