### ISSUE TITLE
spin unable to auth x509 cert, for a secondary self signed root CA

### ISSUE THREAD

**Issue by erickrmz** [spinnaker/spin#111]
In our JKS, we have 2 root CAs, one is third party signed and the other is self signed. Using roer I can auth by providing my spinnaker x509 cert and client, but thats not the case with spin:

```
SPINNAKER_API=https://gate.xxxx.com ~/Downloads/roer-darwin-amd64 -c /spinnaker.crt -k /spinnaker.key pipeline list neo    
INFO[0000] deploy
```

```
$ cat config  
auth:
  enabled: true
  x509:
    certPath: /spinnaker.crt
    keyPath: /spinnaker.key


$ spin application list --gate-endpoint https://gate.xxxx.com                                                                                                                                                         
Error: Get https://gate.xxxx.com/applications: x509: certificate signed by unknown authority

Get https://gate.xxxx.com/applications: x509: certificate signed by unknown authority
```

**Comment by jtk54** [comment]
Which version of `spin` are you using? Which of the two CAs did you use to sign the cert you are using to authenticate with Gate? From the error thrown, it seems like Gate doesn't know about the authority (self signed?) that signed the cert.

**Comment by erickrmz** [comment]
1.13.0 but I also tried building from github.com (so, latest).

I used the self-signed root CA crt and key to sign my client key and csr.

"it seems like Gate doesn't know about the authority (self signed?) that signed the cert.". Yes, that's why I posted an example using roer. I'm sure I'm using the correct key which was signed by my self-signed root CA crt which I uploaded to the JKS

**Comment by jtk54** [comment]
I was able to run through my x509 cert setup yesterday. My guess is that [`roer` overrides the cert behavior to be insecure](https://github.com/spinnaker/roer/blob/69b294aa6c2598de9230e31d0a2376e76a266a12/spinnaker/http.go#L88) and that's what's missing from your spin invocation. You can add a `--insecure` or `-k` flag to your `spin` command to try that out (I had to do this with my self-signed cert when I tried to repro).

**Comment by erickrmz** [comment]
Thanks a lot @jtk54! That makes sense and indeed, if I add --insecure flag, it works!
