### ISSUE TITLE
Existing pipeline not updated on save

### ISSUE THREAD

**Issue by DavidGereb** [spinnaker/spin#120]
### Description
Expected behaviour:
`save` subcommands updates an existing pipeline.
```
$ spin pi save -f pipeline.json
Caching oauth2 token.
Pipeline save succeeded
```
Actual behaviour:
`save` subcommand doesn't update an existing pipeline.
```
$ spin pi save -f pipeline.json
Status: 400 Bad Request, Body: {"error":"Bad Request","exception":"com.netflix.spinnaker.gate.controllers.PipelineController$PipelineException","message":"A pipeline with name myexistingpipeline already exists in application myapplication","status":400,"timestamp":1549378739199}
```
However the save subcommand works fine for the `app` and the `pt` commands.

### Additional info
spin cli: v1.6.0
spinnaker: v1.12.1

**Comment by jtk54** [comment]
Thanks for reporting, will address for pipelines.

**Comment by jtk54** [comment]
https://github.com/spinnaker/spin/pull/124

**Comment by jtk54** [comment]
Will be released in a spin patch.
