### ISSUE TITLE
Could not read configuration file

### ISSUE THREAD

**Issue by ameer00** [spinnaker/spin#147]
If spin config file is not present, it throws the following error, however the command completes successfully. 

```
./spin application save --application-name sample --owner-email example@example.com --cloud-providers kubernetes --gate-endpoint http://localhost:8080/gate
Could not read configuration file from /home/ameer/.spin/config.
Application save succeeded
```

Perhaps the error could be more clear about what it actually uses in the absence on the spin config.

**Comment by jtk54** [comment]
Agreed, the warning is a bit jarring considering the operation succeeds.

**Comment by jtk54** [comment]
https://github.com/spinnaker/spin/pull/153.
