### ISSUE TITLE
Spin create application failed from command line flag

### ISSUE THREAD

**Issue by blackcat-lin** [spinnaker/spin#150]
I upgraded spinnaker to 1.13.0, and when I use spin command to create application and got below error:

spin -k application save --application-name my-app --owner-email <myemailaddress> --cloud-providers "kubernetes"

Encountered an error saving application, task output was: map[startTime:1.554318646992e+12 steps:[map[loopStart:false name:createApplication stageStart:true status:TER
MINAL endTime:1.554318647028e+12 id:1 implementingClass:com.netflix.spinnaker.orca.applications.tasks.UpsertApplicationTask loopEnd:false stageEnd:true startTime:1.554
318647015e+12]] application:my-app endTime:1.554318647042e+12 name:Create Application: my-app status:TERMINAL variables:[map[key:exception value:map[details:map[error:
Unexpected Task Failure errors:[Cannot deserialize instance of `java.lang.String` out of START_ARRAY token                                   
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.netflix.spinnaker.orca.front50.model.Application["cloudProviders"])] stackTrace:java.lang.Ill
egalArgumentException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token                       
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.netflix.spinnaker.orca.front50.model.Application["cloudProviders"])

Any idea what’s wrong? I can managed to run that command in spinnaker 1.12.x version though. I can also run "spin application list" successfully in 1.13.0. Thanks!

**Comment by jtk54** [comment]
https://github.com/spinnaker/spin/pull/154.
