### ISSUE TITLE
Requests to gate do not appear to be correctly encoded

### ISSUE THREAD

**Issue by Chronojam** [spinnaker/spin#167]
Hello; just encountered this today:

```
$ spin --version
1.7.0
```

Consider a pipeline such that
```
# mypipeline.json
{
    "schema": "v2",
    "application": "myApplication", 
    "name": "Trigger And Do Something", 
    "template": {
      "source": "spinnaker://SomeTemplate" 
    },
    "variables": {
      "path": "SomeValue"
    },
    "inherit": ["expectedArtifacts", "stages"],
    "triggers": [],
    "parameters": [],
    "notifications": [],
    "description": "",
    "stages": []
 }
```
Create using 
```
$ spin pipelines save -f mypipeline.json
```

Now attempt an operation using anything that takes a name parameter
eg.
```
# This actually deletes a pipeline named 'Trigger' if it exists.
$ spin pipelines delete -a myApplication -n "Trigger And Do Something"

# Any variation also has the same effect.
$ spin pipelines delete -a myApplication -n "Trigger\ And\ Do\ Something"
$ spin pipelines delete -a myApplication --name 'Trigger And Do Something'
```

However, the follow *does* work:
```
$ spin pipelines delete -a myApplication -n "Trigger%20And%20Do%20Something"
```

imho, the name value here should be encoded before it gets passed off to gate, what do you think?

**Comment by jtk54** [comment]
I couldn't reproduce what you saw on master. I saved two pipelines named `space` and `space delete test` and was able to use double quotes to correctly delete `space delete test`:

```bash
$ ./spin pi list -a app | jq "map(.name)" | grep space
 "space delete test",
  "space"
$ ./spin pi del -a app -n "space delete test"
Pipeline deleted
$ ./spin pi list -a app | jq "map(.name)" | grep space
"space"
```

Can you attempt the same workflow with a spin binary built from 'master' to either verify this has been fixed or something else is at play?

**Comment by Chronojam** [comment]
Thanks @jtk54 

I wasnt able to reproduce this on master, sorry for not checking that first
Ill close this up now, thanks again :+1:
