### ISSUE TITLE
Connection refused to gate endpoint

### ISSUE THREAD

**Issue by MrTrustor** [spinnaker/spin#173]
Hi,

Following #163 and #164, the `--gate-endpoint` flag doesn't seem to be working at all for me?
Whatever value I provide, spin tries to connect to port 9000.

Here is my setup:

```
DECK_POD=$(kubectl -n spinnaker get pods -l \
    cluster=spin-deck,app=spin \
    -o=jsonpath='{.items[0].metadata.name}')
kubectl -n spinnaker port-forward $DECK_POD 8080:9000 

GATE_POD=$(kubectl -n spinnaker get pods -l \
    cluster=spin-gate,app=spin \
    -o=jsonpath='{.items[0].metadata.name}')
kubectl -n spinnaker port-forward $GATE_POD 8084:8084
```

Here are various spin commands I tried with the `--gate-endpoint` flag:

```
$ spin application save --application-name sampleapp --owner-email example@example.com --cloud-providers "kubernetes" --gate-endpoint http://localhost:8080/gate
Could not dial http client, please ensure Gate is running. Failing.
Get http://localhost:9000: dial tcp [::1]:9000: connect: connection refused

$ spin application save --application-name sampleapp --owner-email example@example.com --cloud-providers "kubernetes"
Could not dial http client, please ensure Gate is running. Failing.
Get http://localhost:9000: dial tcp [::1]:9000: connect: connection refused

$ spin application save --application-name sampleapp --owner-email example@example.com --cloud-providers "kubernetes" --gate-endpoint http://127.0.0.1:8084/
Could not dial http client, please ensure Gate is running. Failing.
Get http://localhost:9000: dial tcp [::1]:9000: connect: connection refused
```

I also note that `spin --help` says that the default endpoint is `http://localhost:8084` and that doesn't seem to be the case.

**Comment by jtk54** [comment]
Which version of spin are you using? We cut a 1.7.1 release recently which (should) fix this issue. I also tried to repro from master today and noticed that the commands were honoring `--gate-endpoint`.

I did notice that URLs with trailing slashes broke though. Do you have `localhost:9000` in your configuration?

**Comment by rverma-nikiai** [comment]
@jtk54 facing a similar problem. While my gate endpoint is https one `https://cd-api.niki.ai/login` the error message says
```
spin application list
Could not dial http client, please ensure Gate is running. Failing.
Get http://cd-api.niki.ai/login: dial tcp 52.66.94.71:80: i/o timeout
```

**Comment by jtk54** [comment]
Does this occur for the latest `spin` version?

**Comment by rverma-nikiai** [comment]
Yes with spin 1.7.1

**Comment by MrTrustor** [comment]
@jtk54 Yes, I'm seeing that with 1.7.1. Reverting to 1.6.0 works.
I don't have a local spin configuration (at least not in `~/.spin/config`, is it looking for a config somewhere else?).

**Comment by jtk54** [comment]
~/.spin/config is the default path but there is a flag to point to the config. I've still been unable to repro this with the latest built binary and manually building from source.

Do you have any authentication configured?

**Comment by rodriguezsergio** [comment]
Reverting to 1.6.0 works for me as well. Using x509 authentication.

**Comment by MrTrustor** [comment]
@jtk54 I've sent you an invite for us to debug this together.

**Comment by jtk54** [comment]
Reverted the broken Gate liveness check functionality: https://github.com/spinnaker/spin/pull/176.
