### ISSUE TITLE
spin caching with vpn

### ISSUE THREAD

**Issue by milesmatthias** [spinnaker/spin#183]
My spinnaker instance is behind a VPN. If I attempt to run a spin command without being connected to the VPN, I get an expected 403 Forbidden.

However, after I connect to the VPN, I still get the 403 Forbidden with spin, even though I can curl gate and visit the UI successfully.

Is there a caching store that can be reset in spin? 

I'm using Google OAuth by the way.

**Comment by jtk54** [comment]
Spin caches the oauth2 token in the `~/.spin/config` under the [oauth2 config](https://www.spinnaker.io/guides/spin/cli/#oauth2). You can delete the config to reset the oauth2 context, but you'll have to go through the authentication flow again.

**Comment by jtk54** [comment]
I am not certain that this will alleviate the VPN problems however -- can you provide more detailed information about the VPN configuration and Gate stack traces if resetting the oauth2 config doesn't work?

**Comment by milesmatthias** [comment]
Yea, removing and refreshing my token doesn't help.

I don't have any gate traces because my requests aren't getting to gate.

I'm using the [Cisco Anyconnect client](https://www.cisco.com/c/en/us/products/security/anyconnect-secure-mobility-client/index.html#~stickynav=4) on a mac.

**Comment by milesmatthias** [comment]
I'm not sure this is an issue to fix for spin or not, but I do have a workaround. Use port-forwarding to connect to the gate service.

1. `kubectl port-forward svc/spin-gate 8084:8084`
2. `spin --gate-endpoint http://localhost:8084 pt list`

**Comment by milesmatthias** [comment]
FYI, I figured out that the go DNS resolver wasn't resolving hostnames to the internal IP address that my VPN configured and let me connect to, so I had to add internal IP addresses and hostnames to my `/etc/hosts` to get this to work.
