### ISSUE TITLE
spin pipeline-templates save generates 3 pipeline templates

### ISSUE THREAD

**Issue by johnbenz13** [spinnaker/spin#189]
Using spin 1.7.2 and spinnaker 1.14.2

Step to reproduce:
* Use the default template from [spinnaker documentation ](https://www.spinnaker.io/guides/user/pipeline/pipeline-templates/create/) and save it 

```json
{
  "schema" : "v2",
  "variables": [
  {
    "type": "int",
    "defaultValue": 42,
    "description": "The time a wait stage shall pauseth",
    "name": "timeToWait"
  }
  ],
  "id": "newSpelTemplate",
  "protect": false,
  "metadata": {
    "name": "Variable Wait",
    "description": "A demonstrative Wait Pipeline.",
    "owner": "john@bookaway.com",
    "scopes": ["global"]
  },
  "pipeline": {
    "lastModifiedBy": "anonymous",
    "updateTs": "0",
    "parameterConfig": [],
    "limitConcurrent": true,
    "keepWaitingPipelines": false,
    "description": "",
    "triggers": [],
    "notifications": [],
    "stages": [
    {
      "waitTime": "${ templateVariables.timeToWait }",
      "name": ",My Wait Stage",
      "type": ",wait",
      "refId": ",wait1",
      "requisiteStageRefIds": []
    }
    ]
  }
}
```

* Run ```spin pipeline-templates save --file template.json```

* Go to `Pipeline Templates` tab in Spinnaker UI you'll see 3 instances of the same template

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/846731/59201072-46c83700-8ba2-11e9-9316-e1a7cec0eaf9.png">

**Comment by milesmatthias** [comment]
@johnbenz13 see https://github.com/spinnaker/spinnaker/issues/4443 discussion for an explanation here.

It's expected but not well documented in the UI. It's on the team's radar to improve this.

**Comment by johnbenz13** [comment]
@milesmatthias ok I see,
The problem now is that the pipeline template tagged with latest cannot be deleted, is it a normal behavior as well?

**Comment by milesmatthias** [comment]
that I'm not sure about. I would expect that it could be deleted as long as no pipelines have been created from it. I would close this ticket and open you're unable to delete a pipeline template and if you have not created a pipeline from it.

**Comment by milesmatthias** [comment]
@johnbenz13 1.14.5 got released today which adds these tags.

**Comment by louisjimenez** [comment]
Starting with change [#4561](https://github.com/spinnaker/spinnaker/issues/4561), only the latest version is now listed. However, pipelines can still be made to reference a different version of the template by editing the JSON in the pipeline config screen. For example, if you wanted to reference a version tagged "stable" you can enter spinnaker://my-template-id:stable or if you wanted to reference a template by sha you can do something like spinnaker://my-template-id@sha256:66fe7...

There is now also this issue, [#4563](https://github.com/spinnaker/spinnaker/issues/4563), to create a better versioning UI for templates and updates will be shared there. Thanks!
