### ISSUE TITLE
Intermittent authentication failure with LDAP

### ISSUE THREAD

**Issue by bnutt** [spinnaker/spin#194]
Running spin cli based off master branch. 
Spinnaker Version: 1.14.6

Configured my ~/.spin/config to use ldap as the authentication module. 

Attempting to save/plan pipeline templates or save applications/pipelines **intermittently** fails due to
```
spin pipeline-templates plan --file spinnaker/pipeline.json --config config.yaml
[31mLDAP Authentication Failed[0m
[31mldap authentication failed[0m
```

Verified the user credentials are correct and that the user has proper role access to save the application/pipeline templates.

**Comment by icoolchn** [comment]
@bnutt 
Hey 👍 
       Can you tell me the LDAP configuration , Thanks

**Comment by bnutt** [comment]
This was fixed due to https://github.com/spinnaker/gate/commit/935a3347136727001fa7c89708fe92be23bfb618
