### ISSUE TITLE
spin Authorization Code URL has localhost as redirect_uri

### ISSUE THREAD

**Issue by arafatmohammed** [spinnaker/spin#48]
**oauth2** configured and enabled with GitHub as provider on Spinnaker. It works just fine when someone tries to authenticate while trying to log into Spinnaker.

But when I am trying to use spin-cli with **oauth2** in **~/.spin/config** and running any **spin** commands, the link it provides me with to authenticate and get the acces_token from the browser does not work, since it has 
the  redirect_uri as localhost  **redirect_uri=http%3A%2F%2Flocalhost%3A8085**, this is obviously not working. In my **oauth2** configuration I have the correct **preEstablishedRedirectUri** setup, not sure why spinnaer is not using that.

I replaced and **spin** provided **redirect_uri=http%3A%2F%2Flocalhost%3A8085** with my **preEstablishedRedirectUri** on the browser and it does take me to GitHub to authenticate but I am curious why **spin** has **localhost** as **redirect_uri**.

    ~/.hal/config:
                    authn:
                    oauth2:
                        enabled: true
                        client:
                        clientId: <redacted>
                        clientSecret: <redacted>
                        accessTokenUri: https://github.com/login/oauth/access_token
                        userAuthorizationUri: https://github.com/login/oauth/authorize
                        scope: user:email
                        preEstablishedRedirectUri: https://spinnaker.<redacted>.com:8084/login
                        useCurrentUri: false
                        resource:
                        userInfoUri: https://api.github.com/user
                        userInfoMapping:
                        email: email
                        firstName: ''
                        lastName: name
                        username: login
                        provider: GITHUB

    ~/.spin/config:

                auth:
                enabled: true
                x509:
                    certPath: "/home/ubuntu/certs/bundle.crt"
                    keyPath: "/home/ubuntu/certs/key.pem"

                oauth2:
                    authUrl: "https://github.com/login/oauth/authorize"
                    tokenUrl: "https://github.com/login/oauth/access_token"
                    clientId: <redacted>
                    clientSecret: <redacted>
                    scopes:
                        - user

    $ spin application list
                Navigate to https://github.com/login/oauth/authorize?access_type=offline&approval_prompt=force&client_id=<redacted>&redirect_uri=http%3A%2F%2Flocalhost%3A8085&response_type=code&scope=user&state=state-token and authenticate
                Paste authorization code:

**Comment by jtk54** [comment]
> redirect_uri as localhost redirect_uri=http%3A%2F%2Flocalhost%3A8085, this is obviously not working

Redirecting to localhost is the intended effect of the oauth2 flow in `spin`. Oauth2 in `spin` is separate from oauth2 authentication in Gate. `spin` mediates the token exchange outside of Gate's purview, interacting only with the user and the oauth2 provider. Once `spin` has the token, it adds the token in the `Auth` header to every subsequent request to Gate. [Auth flow section of the design doc](https://docs.google.com/document/d/17Ifm562aypjLSHnNJ02COFv_VMv3spicH-7zMYd-oXE/edit#heading=h.pvyxdlvryggr).

Can you expand on what exactly is not working?

**Comment by arafatmohammed** [comment]
Thanks for your response, I now understand how this works. However, I now see a different issue, when I run the *spin command* it gives me a URL to navigate to get the Authorization Code. After I paste the **Authorization Code** from the browser and paste it, it gives me the following error:

```
$ ./spin application list                           
Navigate to https://github.com/login/oauth/authorize? 
access_type=offline&approval_prompt=force&client_id= . 
<redacted>&redirect_uri=http%3A%2F%2Flocalhost%3A8085&response_type=code&scope=user&state=state-token and authenticate
Paste authorization code:
2832ad5ef5ef4e965da7
OAuth2 Authentication failed.
oauth2: server response missing access_token
```



![3lo](https://user-images.githubusercontent.com/22038514/43338144-341cb97a-919b-11e8-8580-af19048bea9e.png)

We're stuck at the **Exchanges the refresh and access token** part of the 3LO flow. 

Please help me understand this error.

**Comment by jtk54** [comment]
Seems that the library's surfacing of the exception isn't very helpful, I'll have to dig in and debug more thoroughly. We can definitely make `spin`'s reporting/surfacing better (hopefully).

Are there any github oauth2 config settings missing for the `spin` flow to work? I found this section in the docs: https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#redirect-urls might that be the issue?

**Comment by bernardomk** [comment]
Hi @jtk54, I am working with @arafatmohammed in this issue and here's what I found:

If we curl GitHub API from curl, we can get the access_token:

curl -v -X POST https://github.com/login/oauth/access_token?client_id=<client_id>&redirect_uri=http://localhost:8085&client_secret=<client_secret>&access_type=offline&approval_prompt=force&code=<retried_from_spin>

The response we get is: access_token=<access_token>&scope=repo&token_type=bearer.

Not sure if the issue is in spin or golang oauth2 library, we'll try to find out. 

Oauth config (tokenUrl and authUrl, clientId and clientSecret) are correct.in .spin/config

**Comment by bernardomk** [comment]
@jtk54 Believe it or not, adding strings.TrimSpace to the **code** that's read from Prompt (see link bellow) made it work:  
https://github.com/spinnaker/spin/blob/master/command/meta.go#L318

Do you mind me sending you a PR?

**Comment by arafatmohammed** [comment]
Closing the issue now. Thanks @bernardomk and @jtk54

**Comment by moos3** [comment]
hrm I try do get this to work, i'm getting the following after the url curl ```*   Trying 192.30.253.113...
* TCP_NODELAY set
* Connected to github.com (192.30.253.113) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: businessCategory=Private Organization; 1.3.6.1.4.1.311.60.2.1.3=US; 1.3.6.1.4.1.311.60.2.1.2=Delaware; serialNumber=5157550; C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=github.com
*  start date: May  8 00:00:00 2018 GMT
*  expire date: Jun  3 12:00:00 2020 GMT
*  subjectAltName: host "github.com" matched cert's "github.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 Extended Validation Server CA
*  SSL certificate verify ok.
> POST /login/oauth/authorize?access_type=offline&approval_prompt=force&client_id=8e0d4f6bf99a4cfbb022&code_challenge=%9A%9DQ%15%16&redirect_uri=http%3A%2F%2Flocalhost%3A8085&response_type=code&scope=user&state=state-token HTTP/1.1
> Host: github.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Server: GitHub.com
< Date: Mon, 29 Oct 2018 19:58:00 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Status: 400 Bad Request
< X-Request-Id: c39976a3-7a5b-43c2-a200-4d359cc4ef45
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Frame-Options: deny
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
< Expect-CT: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
< Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com; font-src assets-cdn.github.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: assets-cdn.github.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com collector.githubapp.com avatars0.githubusercontent.com avatars1.githubusercontent.com avatars2.githubusercontent.com avatars3.githubusercontent.com github-cloud.s3.amazonaws.com; manifest-src 'self'; media-src 'none'; script-src assets-cdn.github.com; style-src 'unsafe-inline' assets-cdn.github.com
< X-GitHub-Request-Id: F6DB:4F88:A7422:1471FA:5BD76648
<
* Connection #0 to host github.com left intact``` Seems that this is broken in version 1.1.1 of the spinnaker cli.

**Comment by jtk54** [comment]
The URL emitted from spin is intended to be used in the browser to authenticate with the oauth2 provider, though I suspect you could do the same from curl.

Is there a particular reason behind using curl instead of the browser?

**Comment by simeonlam** [comment]
This issue still happening now
```
$ spin application list
Navigate to https://github.com/login/oauth/authorize?access_type=offline&approval_prompt=force&client_id={client_id}&code_challenge={code_challenge}&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A8085&response_type=code&scope=profile+email&state=state-token and authenticate
Paste authorization code:
xxxxxxxxxxxxxxxxx
OAuth2 Authentication failed.
oauth2: server response missing access_token
```
spin version
```
$ spin --version
version 1.7.1
```
I need to copy the access token to `~/.spin/config`
```
auth:
  oauth2:
    cachedToken:
      accesstoken: <token>
```
