### ISSUE TITLE
Creating a new app using spring cli

### ISSUE THREAD

**Issue by rverma-nikiai** [spinnaker/spin#78]
Trying to create a new application using below json
```
{
  "attributes": {
    "accounts": "stage",
    "cloudProviders": "kubernetes",
    "dataSources": {
      "disabled": [],
      "enabled": []
    },
    "email": "rohit.verma@xxx",
    "instancePort": 80,
    "lastModifiedBy": "rohit.verma@xxx",
    "name": "app",
    "user": "rohit.verma@xxx"
  },
  "clusters": {
    "stage": [
      {
        "loadBalancers": [
          "app"
        ],
        "name": "app",
        "provider": "kubernetes",
        "serverGroups": [
          "app-v000"
        ]
      }
    ]
  },
  "name": "app"
}

```
And using commands
`spin application save --file app.json`

results in exception as 
```
 spin application save --file app.json --cloud-providers=kubernetes
Caching oauth2 token.
Overriding application cloud providers with explicit flag values.

Error: Status: 500 , Body: {"error":"Internal Server Error","exception":"org.springframework.http.converter.HttpMessageNotReadableException","message":"Required request body is missing: public java.util.Map com.netflix.spinnaker.gate.controllers.TaskController.task(java.util.Map)","status":500,"timestamp":1538555775004}

Status: 500 , Body: {"error":"Internal Server Error","exception":"org.springframework.http.converter.HttpMessageNotReadableException","message":"Required request body is missing: public java.util.Map com.netflix.spinnaker.gate.controllers.TaskController.task(java.util.Map)","status":500,"timestamp":1538555775004}
```

**Comment by jtk54** [comment]
Which version of the spin CLI are you using?

**Comment by louisvernon** [comment]
I experience the same error with Spin 1.1.1 on Spinnaker 1.10.1

If I take the example [straight from the docs](https://www.spinnaker.io/guides/spin/pipeline/#create-and-update-pipelines-with-save).

```
$ cat test.json 
{
  "isNew": true,
  "keepWaitingPipelines": false,
  "lastModifiedBy": "anonymous",
  "limitConcurrent": true,
  "stages": [
    {
      "comments": "I have no quarrel with ye.",
      "name": "Wait",
      "refId": "1",
      "requisiteStageRefIds": [],
      "type": "wait",
      "waitTime": 30
    }
  ],
  "triggers": [],
  "updateTs": "1541313750451"
}
$ ./spin --gate-endpoint https://spinnaker-api.descarteslabs.com  pipeline save --file test.json
Required pipeline key 'name' missing...

Required pipeline key 'application' missing...

Required pipeline key 'id' missing...

Error: Submitted pipeline is invalid:[...]
```
I add the missing properties.
```
$ cat test.json 
{
  "name": "test pipeline",
  "application": "test",
  "id": "1",
  "isNew": true,
  "keepWaitingPipelines": false,
  "lastModifiedBy": "anonymous",
  "limitConcurrent": true,
  "stages": [
    {
      "comments": "I have no quarrel with ye.",
      "name": "Wait",
      "refId": "1",
      "requisiteStageRefIds": [],
      "type": "wait",
      "waitTime": 30
    }
  ],
  "triggers": [],
  "updateTs": "1541313750451"
}
$ ./spin --gate-endpoint https://spinnaker-api.mydomain.com  pipeline save --file test.json
Error: Status: 500 Internal Server Error, Body: {"error":"Internal Server Error","exception":"org.springframework.http.converter.HttpMessageNotReadableException","message":"Required request body is missing: public void com.netflix.spinnaker.gate.controllers.PipelineController.savePipeline(java.util.Map)","status":500,"timestamp":1541314491148}

Status: 500 Internal Server Error, Body: {"error":"Internal Server Error","exception":"org.springframework.http.converter.HttpMessageNotReadableException","message":"Required request body is missing: public void com.netflix.spinnaker.gate.controllers.PipelineController.savePipeline(java.util.Map)","status":500,"timestamp":1541314491148}
```

**Comment by jtk54** [comment]
I was able to also reproduce this. I'll do an audit this week of the operations surfaced by the spin CLI, seems like there was some breakage around 1.10.x. Thanks for pointing this out.

**Comment by jtk54** [comment]
@louisvernon I walked through this again from scratch and did all the steps you specified in order and was able to save the pipeline. Which authentication methods do you have configured in `spin`? I noticed you are hitting Gate behind SSL, are there any errors in the logs either in Gate or Orca that elucidate what is happening?

**Comment by winstonriley** [comment]
@jtk54 fwiw, this is from the logs of `spin-gate` while trying to save a pipeline (I was able to recreate @louisvernon's issue): https://gist.github.com/winstonriley/4e8d51bc74d10e1046f65227bf1c9a43

**Comment by jtk54** [comment]
That is indeed helpful. I found this in the stack trace:

`com.netflix.spinnaker.gate.security.oauth2.ExternalAuthTokenFilter.doFilter(ExternalAuthTokenFilter.groovy:60)`

I'll enable OAuth2 on Gate and see if I can repro. In the meantime - which OAuth2 providers are you folks using? Do you have x.509/ssl enabled?

**Comment by jtk54** [comment]
Follow up - how are you acquiring and configuring the OAuth2 token in `spin`?

**Comment by louisvernon** [comment]
```
gate:
  endpoint: https://spinnaker-api.mydomain.com
auth:
  enabled: true
  oauth2:
    tokenUrl: https://accounts.google.com/o/oauth2/token
    authUrl: https://accounts.google.com/o/oauth2/auth
    clientId: ""
    clientSecret: ""
    scopes:
    - profile email
    cachedToken:
      accesstoken: ${ACCESS_TOKEN}
      tokentype: ""
      refreshtoken: ${REFRESH_TOKEN}
      expiry: 0001-01-01T00:00:00Z
```

With ACCESS_TOKEN and REFRESH_TOKEN being substituted for the result from `gcloud auth print-access-token` and `gcloud auth print-refresh-token` respectively.

With these settings I can happily list applications/pipelines using `spin` but can't save them.

**Comment by jtk54** [comment]
OK, I have a repro case identical to what you are seeing. I'll work on this today.

**Comment by jtk54** [comment]
It looks like this is related to the OAuth2 token processing. Currently regardless of whether a bearer token is present in the initial request, Gate redirects the caller several times to walk through the OAuth2 flow. When redirected, `spin` does not re-send the POST payload body. It seems incorrect that Gate is asking the caller to walk through the flow even though there is a token present in `spin` calls. I'm investigating ways to prevent Gate from asking the caller to do the duplicate work.

**Comment by jtk54** [comment]
PR here: https://github.com/spinnaker/spin/pull/86.

**Comment by jtk54** [comment]
Will be out in a `spin` release likely next week.

**Comment by louisvernon** [comment]
```
 $ ./spin --gate-endpoint https://spinnaker-api.mydomain.com  pipeline save --file test.json
Caching oauth2 token.
Pipeline save succeeded
```
Woo! Thanks @jtk54.

**Comment by jtk54** [comment]
Great! Good to hear.
