### ISSUE TITLE
Unable to build spin

### ISSUE THREAD

**Issue by kskewes** [spinnaker/spin#80]
Have just done a fresh clone of this repo and am unable to complete `go build -v`.
```
$ go build -v
:~/go/src/github.com/spinnaker/spin$ go build -v
github.com/spinnaker/spin/cmd/gateclient
# github.com/spinnaker/spin/cmd/gateclient
cmd/gateclient/client.go:310:35: too many arguments in call to config.Exchange
        have (context.Context, string, "golang.org/x/oauth2".AuthCodeOption)
        want (context.Context, string)
```

link to error: https://github.com/spinnaker/spin/blob/master/cmd/gateclient/client.go#L310

**Comment by jtk54** [comment]
Try updating your oauth2 lib dependency with `go get -u golang.org/x/oauth2` and then rebuilding.

**Comment by kskewes** [comment]
Thanks! I had to remove existing golang oauth2 first else it would fail to update.

**Comment by jtk54** [comment]
At some point in the future when we hit critical dependency mass, we will add dependency vendoring support to avoid issues like this. Let us know if you continue to see dependency version issues like this.

**Comment by kskewes** [comment]
Sure. Cheers.

**Comment by kskewes** [comment]
Sure. Cheers.
